# Generated by Django 3.2.4 on 2021-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.FileField(upload_to='news')),
                ('content', models.TextField(verbose_name='content')),
                ('long_description', models.TextField(verbose_name='long_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
